apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  labels:
    app.kubernetes.io/name: mysql-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-router
    spec:
      containers:
        - name: mysql-router
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "600m"
              memory: "2Gi"
          env:
            - name: MYSQL_HOST
              value: "mysql-headless-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_INNODB_CLUSTER_MEMBERS
              value: "2"
          image: mysql/mysql-router:8.0.28
          imagePullPolicy: IfNotPresent
          ports:
            - name: rw
              protocol: TCP
              containerPort: 6446
            - name: ro
              protocol: TCP
              containerPort: 6447
          readinessProbe:
            tcpSocket:
              port: 6446
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: 6446
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 60
