version: 2
jobs:
  build_frontend:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - run:
          name: Build and push frontend application image
          command: |
            git clone https://github.com/kirubakarthikeyan/spring-petclinic-angular.git
            cd ./spring-petclinic-angular
            TAG=v$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/petclinic_frontend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_frontend:$TAG
  build_backend:
    docker:
      - image: cimg/openjdk:17.0.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - run:
          name: Build and push backend application image
          command: |
            git clone https://github.com/spring-petclinic/spring-petclinic-rest.git
            cd ./spring-petclinic-rest
            ./mvnw clean install
            TAG=v$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/petclinic_backend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_backend:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build_frontend
      - build_backend
