version: 2
jobs:
  build_frontend:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            git clone https://github.com/kirubakarthikeyan/spring-petclinic-angular.git
            cd ./spring-petclinic-angular
            TAG=v$CIRCLE_BUILD_NUM
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/petclinic_frontend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_frontend:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build_frontend
