# THIS IS FOR DEMO PURPOSE, SECRETS SHOULD NOT BE COMMITED
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: UGFzc3dvcmQkMTIzNDU2 # Password$123456
  admin-password: UGFzc3dvcmQkMTIzNDU2 # Password$123456
  username: cm9vdA== # root
