apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-deployment.yaml
  - backend-service.yaml
namespace: default
images:
  - name: docker.io/springsandbox/petclinic_backend
    newName: docker.io/springsandbox/petclinic_backend
    newTag: v12
