apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
namespace: default
images:
  - name: docker.io/springsandbox/petclinic_frontend
    newName: docker.io/springsandbox/petclinic_frontend
    newTag: v4
