apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- backend-deployment.yaml
- backend-service.yaml
namespace: default
images:
- newName: docker.io/springsandbox/petclinic_backend
  newTag: v33
- name: docker.io/springsandbox/petclinic_backend
  newName: docker.io/springsandbox/petclinic_backend
  newTag: v12
- name: docker.io/springsandbox/petclinic_frontend
  newName: docker.io/springsandbox/petclinic_frontend
  newTag: v4
