apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- backend-deployment.yaml
- backend-service.yaml
namespace: default
images:
- name: docker.io/springsandbox/petclinic_backend
  newTag: e187b88
- name: docker.io/springsandbox/petclinic_frontend
  newTag: e23f5a4
