apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app.kubernetes.io/name: spring-application
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-application
    spec:
      containers:
        - name: spring-application
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: MYSQL_HOST
              value: "mysql-router-service"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PORT
              value: "6446"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          image: docker.io/springsandbox/demo:v0.5beta
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          #TODO:// Add liveness probe and readiness probe here
