apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: spring-application
  type: ClusterIP
  ports:
    - name: spring-service
      protocol: TCP
      port: 8080
      targetPort: 8080
